### ISSUE TITLE
Bot Not Functioning Properly

### ISSUE THREAD

**Issue by wariomanguy** [lundylizard/lobster#23]
The bot seems to be connecting to voice channels when a song is queued, then frequently disconnecting and reconnecting semi-rapidly. This seems to be occurring regardless of the source the music is queued from and permissions given to the bot.

It was working fine when I used it a few weeks ago.

**Comment by lundylizard** [comment]
Hi, sorry for responding so late, I fixed this a few days ago, Discord rolled out a breaking change to audio connections.
In the future you will reach me quicker by joining my discord https://discord.gg/Hk5YP5AWhW or messaging me directly `lundylizard#1337`
